version: '3'
services:
  mongo_db:
    container_name: db-container
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
  user_app:
    container_name: user_service
    restart: always
    build: ./user-service
    ports:
      - "3000:3000"
    links:
      - mongo_db
      - post_app
    depends_on:
      - mongo_db
      - post_app
  
  post_app:
    container_name: post_service
    restart: always
    build: ./post-service
    ports:
      - "3001:3001"
    links:
      - mongo_db
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}