version: '3'
services:

  #Zookeeper Service.
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    restart: "no"
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: zookeeper

  #Kafka Service
  # kafka:
  #   image: 'bitnami/kafka:latest'
  #   container_name: kafka-broker
  #   restart: "no"
  #   ports:
  #     - '9092:9092'
  #     - '29092:29092'
  #   environment:
  #     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,PLAINTEXT_HOST://:9092
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=PLAIN://kafka:29092,PLAIN://localhost:9092
  #     - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #   depends_on:
  #     - "zookeeper"
  kafka:
      image: confluentinc/cp-kafka:latest
      container_name: kafka-broker
      ports:
        - "9092:9092"
        - "29092:29092"
      depends_on:
        - zookeeper
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
        ALLOW_PLAINTEXT_LISTENER: 'yes'
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

  #schema
  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - "8081:8081"
    environment:
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181"
  
  #mongodb
  mongo_db:
    container_name: db-container
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
  
  #user
  user_app:
    container_name: user_service
    restart: always
    build: ./packages/user-service
    ports:
      - "3000:3000"
    links:
      - mongo_db
      - post_app
    depends_on:
      - mongo_db
      - kafka
      - post_app

  #post
  post_app:
    container_name: post_service
    restart: always
    build: ./packages/post-service
    ports:
      - "3001:3001"
    links:
      - mongo_db
    depends_on:
      - kafka
      - mongo_db

volumes:
  mongo_db: {}
